### ISSUE TITLE
I can't use the plugin or client.

### ISSUE THREAD

**Issue by Asoku** [TotalFreedom/BukkitTelnet#16]
When I try to connect to my server with the client, It gives me a error that looks like this.

Connecting to 5.135.145.49:1498...
Connection refused: connect
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:182)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:203)
	at me.StevenLawson.BukkitTelnetClient.BTC_ConnectionManager$2.run(BTC_ConnectionManager.java:185)
	at java.lang.Thread.run(Unknown Source)

Disconnected.

I think it is a error with the port, Can anyone help me?

**Comment by Asoku** [comment]
Don't need it anymore.

**Comment by untuned** [comment]
What was the resolution? This is happening to me as well.

**Comment by JeromSar** [comment]
@Untuned This seems like a simple TCP connection error. You might not be able to reach the BukkitTelnet server with the given IP/port.

**Comment by linktlh** [comment]
I actually have the same issue... but I know for certain my ports are open but for some reason, I am unable to access the server via any telnet client. Currently, I have every port open but it seems that's not the issue. another thing that may or may not be notable I am able to connect to the default HTTPd port. I've tried the default port in the config, port 23, and port 31415. none of which seem to actually reach outside the instance.
