### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/BukkitTelnet#5]
2015-05-14 16:40:00,754 ERROR An exception occurred processing Appender BukkitTelnet java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
at java.util.HashMap$KeyIterator.next(HashMap.java:956)
at me.StevenLawson.BukkitTelnet.TelnetLogAppender.append(TelnetLogAppender.java:54)
at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1011)
at net.minecraft.server.v1_8_R2.LoginListener$LoginHandler.fireEvents(LoginListener.java:274)
at net.minecraft.server.v1_8_R2.LoginListener$2.run(LoginListener.java:172)
at java.lang.Thread.run(Thread.java:745)

Read more: http://totalfreedom.boards.net/thread/23367/worldedit-crashing#ixzz3a8t0Grgr

**Comment by JeromSar** [comment]
Fixed in latest build.
